### PR TITLE
Prevent invalid inputs from returning `true`.

### LINKED ISSUE #2: The ipv4 doesn't work correctly.
I ran the following tests and they did not result correctly. For example `$this->assertTrue($cidrMatch->match($addr, '10.0.0.1/8'));` is `True` but it returns `False`.

```
        $cidrMatch = new CIDRmatch();
        // $this->assertTrue($cidrMatch->match($addr, '10.0.0.1/8'));
        // $this->assertTrue($cidrMatch->match($addr, '10.0.0.10/8'));
        // $this->assertTrue($cidrMatch->match($addr, '10.5.5.0/16'));
        // $this->assertFalse($cidrMatch->match($addr, '10.4.5.0/16'));
        // $this->assertTrue($cidrMatch->match($addr, '10.4.5.0/15'));
```

[Symfony/IpUtils](https://github.com/symfony/http-foundation/blob/master/IpUtils.php) has a good test coverage and works perfectly. Recommend using that one.

### PR DESCRIPTION
**Pull request by rinogo**
Also fixes Travis Build to use Ubuntu Trusty and recent PHP versions. Resolves #2, #3, #4.

### CODE REVIEW

**Comment by tholu** [comment]
@rinogo Thanks for your PR! Can you add Travis Builds for newer PHP versions and verify that it works?

**Comment by rinogo** [comment]
Hi @tholu, I haven't used Travis before, so it took me a bit to figure out how to get it all working. But all checks seem to be working now.

**Comment by tholu** [comment]
@rinogo Can you allow edits for maintainers? https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by rinogo** [comment]
@tholu - This is what I see on the PR - do I need to enable this setting somewhere else?
image

**Comment by tholu** [comment]
@rinogo Looks good, will check if I can add some commits to your branch to fix some outstanding issues.

**Pull request merged**
